# Use the official MLflow image as the base
FROM ghcr.io/mlflow/mlflow:latest

# Install psycopg2 and any other necessary dependencies
RUN pip install psycopg2-binary

# Expose the default MLflow port
EXPOSE 5000

# Start the MLflow server
ENTRYPOINT ["mlflow"]
