triggers:
- description: null
  envs: []
  last_enabled_at: 2025-06-23 10:16:46.818512+00:00
  name: ml_regression_pipeline_trigger
  pipeline_uuid: ml_regression_pipeline
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2025-06-23 10:16:00+00:00
  status: active
  token: 3b3832eb8caa46ffb5fdcbab06f48681
  variables: {}
